In [1]:
import numpy as np
from qutip import about, basis, rand_ket, tensor
from qutip_qip.operations import Measurement
from qutip_qip.operations.gates import gate_sequence_product
from qutip_qip.qasm import read_qasm, print_qasm

In [2]:
path = "swap.qasm"
qasm_file = open(path, "r")
# print(qasm_file.read())

In [3]:
qc = read_qasm(path, mode="qiskit", version="2.0")
gate_sequence_product(qc.propagators())

c:\Users\Owner\anaconda3\Lib\site-packages\qutip_qip\qasm.py:189: UserWarning: Unknown parsing mode, using the default mode instead.
  warnings.warn(
c:\Users\Owner\anaconda3\Lib\site-packages\qutip_qip\qasm.py:279: UserWarning: "qelib1.inc"not found, ignored.
  warnings.warn(command[1] + "not found, ignored.")


Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]

In [4]:
print_qasm(qc)

// QASM 2.0 file generated by QuTiP

OPENQASM 2.0;
include "qelib1.inc";

qreg q[2];

cx q[1],q[0];
cx q[0],q[1];
cx q[1],q[0];


## Custom Gates

In [11]:
path = "swap_custom.qasm"
qasm_file = open(path, "r")
print(qasm_file.read())

// SWAP gate defined as a custom gate.

OPENQASM 2.0;
include "qelib1.inc";

qreg q[2];
creg c[2];

gate swap a, b{
cx b, a;
cx a, b;
cx b, a;
}

swap q[0], q[1]

measure q -> c


In [6]:
qc = read_qasm(path)

In [7]:
qc.run(tensor(basis(2, 0), basis(2, 1)))

Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]]

## Measurements and Classical Control

In [8]:
path = "teleportation.qasm"
qasm_file = open(path, "r")
qasm_str = qasm_file.read()
# print(qasm_str)

In [9]:
teleportation = read_qasm(qasm_str, strmode=True)

c:\Users\Owner\anaconda3\Lib\site-packages\qutip_qip\qasm.py:846: UserWarning: Information about individual registers is not preserved in QubitCircuit
  warnings.warn(


In [10]:
state = tensor(rand_ket(2), basis(2, 0), basis(2, 0))

initial_measurement = Measurement("start", targets=[0])
_, initial_probabilities = initial_measurement.measurement_comp_basis(state)

state_final = teleportation.run(state)

final_measurement = Measurement("start", targets=[2])
_, final_probabilities = final_measurement.measurement_comp_basis(state_final)

np.testing.assert_allclose(initial_probabilities, final_probabilities)